/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.formatter.FormatterTestHelper
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslFormattingTest {
	@Inject
	extension FormatterTestHelper

	@Test
	def void formatTest() {
		assertFormatted[
			expectation = '''
				Model {
					assert check has no error
					
					assert check has error
				}
			'''
			toBeFormatted = '''
				Model {
					assert check has no error
					
					assert check has error
				}
			'''
		]
	}
}
